version: '3'
services:
  user_service:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/code/app
    ports:
      - 4001:8000
    networks:
      - fss-network
networks:
  fss-network:
    external: true
